---
title: "analysis"
author: "Aji John"
date: "2/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r }
library(tidyverse)
```

## Including Plots

You can also embed plots, for example:

```{r , echo=FALSE}
predictions_yolo <- read_csv('./data/results_yolo.csv')
exif_data <- read_csv('./data/exif-aug2020.csv')
```

```{r , echo=FALSE}
library(readr)
results_yolo <- read_csv("data/results_yolo.csv", 
    col_names = FALSE)
results_yolo$filename <- substr(results_yolo$X1,13,100)
write_csv(results_yolo,file = 'data/results_yolo.csv')
#View(results_yolo)
```


```{r , echo=FALSE}
library(readr)
results_revised <- read_csv("data/results_yolo.csv", 
    col_names = TRUE)
filtered_columns <- results_revised %>% dplyr::select ('X2','X3','X4','X5','X6','X7','X8','filename') %>% as.data.frame()
```

```{r , echo=FALSE}
filtered_longer <- filtered_columns %>%
  pivot_longer(!filename, names_to = "species", values_to = "species_name")  %>% as.data.frame()
```  
  
  
```{r , echo=FALSE}
key_file_count <- filtered_longer %>% filter(!str_detect(species_name, "Done.")) %>% group_by(filename) %>% count() %>% as.data.frame()
colnames(key_file_count) <- c('file_name','count')
```  

```{r , echo=FALSE}
species_file_count <- filtered_longer %>% filter(!str_detect(species_name, "Done.")) %>% group_by(filename)  %>% as.data.frame()
colnames(species_file_count) <- c('file_name','species',"species_name")
```  

```{r , echo=FALSE}
new_file_species <- merge(exif_data, species_file_count, by="file_name")
```  

```{r , echo=FALSE}
new_file_species_df <- new_file_species %>% 
  separate(species_name, c("species_abund","sp1","sp2"), sep = "\\s+") %>%
  mutate(species_nname = paste(sp1,sp2),noofsp=as.numeric(species_abund)) %>% as.data.frame()
```  
Number of flower
```{r , echo=FALSE}
new_file_species_df %>% group_by(file_name, gps_altitude) %>% summarise (nos=n()) %>%ggplot(aes(gps_altitude, nos)) + geom_point() +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Elevation (m)' , y="# Flower species / photo",fill="Species name") +
  theme(legend.position = "bottom")

nofflo <- new_file_species_df %>% group_by(file_name, gps_altitude) %>% summarise (nos=n()) %>%ggplot(aes(gps_altitude, nos)) + geom_point( size = 5,alpha = 0.5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 24) +
   labs(x='Elevation (m)' , y="# Flower species / photo",fill="Species name") +
  theme(legend.position = "bottom")

nofflo
ggsave("figs/species-richness.png",  width = 35, height = 25, units = "cm")

```  


```{r , echo=FALSE}
 new_file_species_mod_df <- new_file_species_df

#  [1] "American Bistorts"    "Bracted Louseworts"  
# [3] "Magenta Paintbrushs"  "Mountain Daisys"     
# [5] "Sitka Valerians"      "Subalpine Lupines"   
# [7] "Western Anemone"      "Western Anemones"    
# [9] "Mountain Daisy"       "Sitka Valerian"      
# [11] "American Bistort"     "Subalpine Lupine"    
# [13] "Cascade Asters"       "Broadleaf Arnica"    
# [15] "Sharptooth Angelica"  "North Mircoseris"    
# [17] "Grays Lovage"         "Grays Lovages"       
# [19] "Magenta Paintbrush"   "Bracted Lousewort"   
# [21] "Broadleaf Arnicas"    "Cascade Aster"       
# [23] "Sharptooth Angelicas" "North Mircoseriss"

# update the names 
new_file_species_mod_df[new_file_species_mod_df$species_nname=='American Bistorts',]$species_nname<- 'American Bistort'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Magenta Paintbrushs',]$species_nname<- 'Magenta Paintbrush'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Sitka Valerians',]$species_nname<- 'Sitka Valerian'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Cascade Asters',]$species_nname<- 'Cascade Aster'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Broadleaf Arnicas',]$species_nname<- 'Broadleaf Arnica'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Sharptooth Angelicas',]$species_nname<- 'Sharptooth Angelica'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Bracted Louseworts',]$species_nname<- 'Bracted Lousewort'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Mountain Daisys',]$species_nname<- 'Mountain Daisy'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Western Anemones',]$species_nname<- 'Western Anemone'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='North Mircoseriss',]$species_nname<- 'North Mircoseris'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Grays Lovages',]$species_nname<- 'Grays Lovage'
new_file_species_mod_df[new_file_species_mod_df$species_nname=='Subalpine Lupines',]$species_nname<- 'Subalpine Lupine'










``` 
flowering  densities

```{r , echo=FALSE}
new_file_species_mod_df %>% group_by(file_name, gps_altitude) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_nname), alpha = 0.5,size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Elevation (m)' , y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")

fd  <- new_file_species_mod_df %>% group_by(file_name, gps_altitude) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_nname), alpha = 0.5,size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 24) +
   labs(x='Elevation (m)' , y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")

ggsave("figs/species-density.png",  width = 45, height = 25, units = "cm")
``` 

```{r }
library(patchwork)
(nofflo  | fd)+ plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')  &
  theme(legend.position='bottom')

ggsave("figs/combineflowerprese.jpg", width = 40, height = 20, units = "cm")

```

Add  temporal 


lubridate::as_datetime(new_file_species_mod_df$datetime,format='%Y:%m:%d %H:%M:%S')

```{r , echo=FALSE}
daylabel  <- c("23"="August 23","27"="August 27", "30"="August 30")
new_file_species_mod_df %>% mutate(dt= lubridate::as_datetime(datetime,format='%Y:%m:%d %H:%M:%S') ) %>%
  mutate(mnth= lubridate::month(dt),day= lubridate::day(dt)) %>%
  group_by(file_name, gps_altitude) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_nname), size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank(),
          panel.spacing.x=unit(3, "lines"),panel.spacing.y=unit(5, "lines")) + theme_minimal(base_size = 24) +
  facet_wrap(.~day,labeller = labeller(day=daylabel))+
   labs(x='Elevation (m)' ,size="", y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")
ggsave("figs/species-densitytemporal.png",  width = 45, height = 25, units = "cm")
``` 


flowering  densities

```{r , echo=FALSE}
new_file_species_df %>% group_by(file_name, gps_altitude) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_nname)) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Elevation (m)' , y="Flower density / photo",fill="Species name") +
  theme(legend.position = "bottom")


``` 


```{r , echo=FALSE}
ggplot(new_file_species_df, aes(gps_altitude, noofsp)) + geom_point() +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Elevation (m)' , y="Number of species per picture",fill="Species name") +
  theme(legend.position = "bottom")

```  

```{r , echo=FALSE}
ggplot(new_file_species_df, aes(gps_altitude, noofsp)) + geom_bar(aes(fill = species_nname), 
                                              width = 0.4, position = position_dodge(width=0.5), stat="identity") +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Altitude (m)' , y="Number of species",fill="Species name") +
  theme(legend.position = "bottom")
  ggsave("figs/species-distribution.png",  width = 35, height = 25, units = "cm")
```  

```{r , echo=FALSE}
ggplot(new_file_species_df, aes(gps_altitude, noofsp)) + 
  geom_bar(aes(fill = species_nname), 
                                              width = 1, position = position_dodge(width=0.5), stat="identity") +
  geom_point(aes(color=species_nname))+
    theme(legend.position="top", legend.title = "",
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Altitude (m)' , y="Number of detected species",fill="", color="") +
  theme(legend.position = "bottom")
  ggsave("figs/species-distribution-smoothed.png",  width = 35, height = 25, units = "cm")
```  

```{r , echo=FALSE}
new_file <- merge(exif_data, key_file_count, by="file_name")
```  

```{r , echo=FALSE}
new_file %>% ggplot() + geom_point(aes(gps_altitude,count))  + theme_minimal(base_size = 24) +
  labs(x='Altitude (m)' , y="Number of species") +
  theme_minimal()
   
``` 
```{r , echo=FALSE}
new_file %>% ggplot(aes(x = gps_altitude, y = count, label = count)) +
  geom_bar(stat = "identity") +
  geom_text(size = 3, position = position_stack(vjust = 0.5))
``` 

```{r , echo=FALSE}
library(plotly)
new_file %>% ggplot() + geom_point(aes(gps_altitude,count))  + theme_minimal(base_size = 24) +
  labs(x='Altitude (m)' , y="Number of species")
   ggplotly()
``` 
```{r , echo=FALSE}
library(plotly)
new_file %>% 
  ggplot() + geom_point(aes(gps_altitude,count))  + theme_minimal(base_size = 24) +
  labs(x='Altitude (m)' , y="Number of species")
   #ggplotly()
``` 

# 
```{r , echo=FALSE}
new_file %>% ggplot() + 
  geom_smooth(span = 0.5,aes(gps_altitude,count))  + theme_minimal(base_size = 24) +
  labs(x='Altitude (m)' , y="Number of species")+
  ggpubr::theme_cleveland()
   ggsave("figs/number-species-smoothed.png",  width = 30, height = 20, units = "cm")
```  

```{r , echo=FALSE}

summary(lm(data=new_file,formula = count~gps_altitude))

new_file %>% ggplot() + 
  geom_point(aes(gps_altitude,count)) +
  geom_smooth(method = "lm",span = 0.5,aes(gps_altitude,count))  + theme_minimal(base_size = 24) +
  labs(x='Altitude (m)' , y="Number of species")+
  ggpubr::theme_cleveland()
   ggsave("figs/number-species-smoothed-lm.png",  width = 30, height = 20, units = "cm")
```  

```{r , echo=FALSE}
new_file %>% mutate(dt = lubridate::as_date(datetime), ele= round(new_file$gps_altitude)) %>% 
  ggplot() + geom_point(span = 0.65,aes(dt,count,color=as.factor(ele)))  + theme_minimal(base_size = 24) +
  theme(legend.position = "bottom") +
  labs(x='Altitude (m)' , y="Count",color=NULL)
   
```  


```{r , echo=FALSE}
new_file %>% mutate(dt = lubridate::as_date(datetime), ele= round(new_file$gps_altitude)) %>% 
  ggplot() + geom_point(span = 0.65,aes(dt,count))  + theme_minimal(base_size = 24) +
  labs(x='Altitude (m)' , y="Count",color=NULL)
   
```  

# Do it for Mask R-CNN

```{r , echo=FALSE}
predictions_mrcnn<- read_csv('./data/maskr-cnn-pred.csv')
predictions_rnet<- read_csv('./data/retinanet-pred.csv')

names(predictions_mrcnn) <- c('file_name','species_name','probability')
names(predictions_rnet) <- c('file_name','species_name','probability')
```


```{r , echo=FALSE}
new_file_species_mrcnn <- merge(exif_data, predictions_mrcnn, by="file_name")

new_file_species_mrcnn %>% group_by(file_name, gps_altitude,species_name) %>% summarise (nos=n()) %>%  group_by(file_name,gps_altitude) %>% summarise (nos=n()) %>%
  ggplot(aes(gps_altitude, nos)) + geom_point() +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Elevation (m)' , y="# Flower species / photo",fill="Species name") +
  theme(legend.position = "bottom")

noofflowmrcnn <- new_file_species_mrcnn %>% group_by(file_name, gps_altitude,species_name) %>% summarise (nos=n()) %>%  group_by(file_name,gps_altitude) %>% summarise (nos=n()) %>%
  ggplot(aes(gps_altitude, nos)) + geom_point( alpha = 0.5,size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 24) +
   labs(x='Elevation (m)' , y="# Flower species / photo",fill="Species name") +
  theme(legend.position = "bottom")

fdmrcnn  <-new_file_species_mrcnn %>% group_by(file_name, gps_altitude,species_name)  %>% summarise (noofsp=n()) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_name),alpha = 0.5, size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 24) +
   labs(x='Elevation (m)' , y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")

```  

Save for m-rcnn

```{r }
library(patchwork)
(noofflowmrcnn  | fdmrcnn)+ plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')  &
  theme(legend.position='bottom')

ggsave("figs/combineflowerprese-mrcnn.jpg", width = 40, height = 20, units = "cm")

```
'FD by date M-RNN


```{r , echo=FALSE}

new_file_species_mrcnn %>% mutate(dt= lubridate::as_datetime(datetime,format='%Y:%m:%d %H:%M:%S') ) %>%
  mutate(mnth= lubridate::month(dt),day= lubridate::day(dt)) %>%
   group_by(file_name, gps_altitude,species_name,dt,mnth,day)  %>% summarise (noofsp=n()) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_name), alpha = 0.5,size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank(),
          panel.spacing.x=unit(3, "lines"),panel.spacing.y=unit(5, "lines")) + theme_minimal(base_size = 24) +
  facet_wrap(.~day,labeller = labeller(day=daylabel))+
   labs(x='Elevation (m)' ,size="", y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")
ggsave("figs/species-densitytemporalmrcnn.png",  width = 45, height = 25, units = "cm")
``` 


```{r , echo=FALSE}
new_file_species_rnet <- merge(exif_data, predictions_rnet, by="file_name")

new_file_species_rnet %>%  group_by(file_name, gps_altitude,species_name) %>% summarise (nos=n()) %>%  group_by(file_name,gps_altitude) %>% summarise (nos=n()) %>%
  ggplot(aes(gps_altitude, nos)) + geom_point() +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 18) +
   labs(x='Elevation (m)' , y="# Flower species / photo",fill="Species name") +
  theme(legend.position = "bottom")


noofflowrnet<- new_file_species_rnet %>% group_by(file_name, gps_altitude,species_name) %>% summarise (nos=n()) %>%  group_by(file_name,gps_altitude) %>% summarise (nos=n()) %>%
  ggplot(aes(gps_altitude, nos)) + geom_point(alpha = 0.5, size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 24) +
   labs(x='Elevation (m)' , y="# Flower species / photo",fill="Species name") +
  theme(legend.position = "bottom")

fdrnet <-new_file_species_rnet %>% group_by(file_name, gps_altitude,species_name)  %>% summarise (noofsp=n()) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_name), alpha = 0.5,size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank()) + theme_minimal(base_size = 24) +
   labs(x='Elevation (m)' , y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")
```  
Save for r-net

```{r }
library(patchwork)
(noofflowrnet  | fdrnet)+ plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')  &
  theme(legend.position='bottom')

ggsave("figs/combineflowerprese-rnet.jpg", width = 40, height = 20, units = "cm")

```

'FD by date R-Net


```{r , echo=FALSE}

new_file_species_rnet %>% mutate(dt= lubridate::as_datetime(datetime,format='%Y:%m:%d %H:%M:%S') ) %>%
  mutate(mnth= lubridate::month(dt),day= lubridate::day(dt)) %>%
   group_by(file_name, gps_altitude,species_name,dt,mnth,day)  %>% summarise (noofsp=n()) %>%ggplot() + geom_point(aes(gps_altitude, noofsp,color=species_name), alpha = 0.5,size = 5) +  
    theme(legend.position="top", legend.title = 
              element_blank(),axis.title.x=element_blank(), 
          axis.title.y=element_blank(),
          panel.spacing.x=unit(3, "lines"),panel.spacing.y=unit(5, "lines")) + theme_minimal(base_size = 24) +
  facet_wrap(.~day,labeller = labeller(day=daylabel))+
   labs(x='Elevation (m)' ,size="", y="Flower density / photo",color="Species") +
  theme(legend.position = "bottom")
ggsave("figs/species-densitytemporalrnet.png",  width = 45, height = 25, units = "cm")
```




Do a R2 test
```{r , echo=FALSE}
noffrnet <- new_file_species_rnet %>% group_by(file_name, gps_altitude,species_name) %>% summarise (nos=n()) %>%  group_by(file_name,gps_altitude) %>% summarise (nos=n()) %>% as.data.frame()
noffmrcnn <- new_file_species_mrcnn %>% group_by(file_name, gps_altitude,species_name) %>% summarise (nos=n()) %>%  group_by(file_name,gps_altitude) %>% summarise (nos=n()) %>% as.data.frame()
noffyolo<-  new_file_species_df %>% group_by(file_name, gps_altitude) %>% summarise (nos=n()) %>% as.data.frame()

rcnnandyoloandrnetbycommon <- merge(noffyolo,noffmrcnn,by='file_name')
names(rcnnandyoloandrnetbycommon) <- c('file_name','gps_altitude_yolo','nosyolo','gps_altitude_mrcnn','nosmrcnn')
rcnnandyoloandrnetbycommon <- merge(rcnnandyoloandrnetbycommon,noffrnet,by='file_name')
names(rcnnandyoloandrnetbycommon) <- c('file_name','gps_altitude_yolo','nosyolo',
                                       'gps_altitude_mrcnn','nosmrcnn',
                                       'gps_altitude_rnet','nosrnet')

rcnnandyoloandrnet <- cbind(noffmrcnn$nos,noffyolo$nos,noffrnet$nos)
dfnoofsmethods <- as.data.frame(rcnnandyoloandrnet)
names(dfnoofsmethods) <- c('noofspsmrcnn','noofspsyolo','noofspsrnet')

library(psych)
pairs.panels(dfnoofsmethods[1:3])  # select columns 1-3
```
```{r , echo=FALSE}
COR <- rcnnandyoloandrnetbycommon[c('nosyolo',
                                       'nosmrcnn',
                                       'nosrnet')]
names(COR) <- c('Yolo-# of Species',
                                       'M-RCNN-# of Species',
                                       'RetinaNet-# of Species')
library(psych)
pairs.panels(rcnnandyoloandrnetbycommon[c('nosyolo',
                                       'nosmrcnn',
                                       'nosrnet')])  # select three
```

```{r , echo=FALSE}

library(psych)
pairs.panels(COR)  # select three
```

```{r , echo=FALSE}

library(psych)
library(PerformanceAnalytics)

chart.Correlation(COR)  # select three
```

```{r , echo=FALSE}

library(PerformanceAnalytics)
chart.Correlation(rcnnandyoloandrnetbycommon[c('nosyolo',
                                       'nosmrcnn',
                                       'nosrnet')])  # select three
```

```{r , echo=FALSE}
library(PerformanceAnalytics)
chart.Correlation(dfnoofsmethods[1:3])

```